// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDahxGAkHMgXjLqmbyPXAQNNDoxHGwezsQ',
    appId: '1:626775340202:web:d2262e0e6ded9840914cd3',
    messagingSenderId: '626775340202',
    projectId: 'epsib3cdaia',
    authDomain: 'epsib3cdaia.firebaseapp.com',
    storageBucket: 'epsib3cdaia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDY7WQ6RnKQqUVAquKoLmZmR432a-0SQo',
    appId: '1:626775340202:android:019a90d10564bffa914cd3',
    messagingSenderId: '626775340202',
    projectId: 'epsib3cdaia',
    storageBucket: 'epsib3cdaia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-TYy3dMFieQZ6NA79DIo_OB8xB-3cg5Y',
    appId: '1:626775340202:ios:0d94f1957b4ff9e3914cd3',
    messagingSenderId: '626775340202',
    projectId: 'epsib3cdaia',
    storageBucket: 'epsib3cdaia.appspot.com',
    iosClientId: '626775340202-net3702f0i7gubo0n9qh48mqv6atrsd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectepsi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-TYy3dMFieQZ6NA79DIo_OB8xB-3cg5Y',
    appId: '1:626775340202:ios:0d94f1957b4ff9e3914cd3',
    messagingSenderId: '626775340202',
    projectId: 'epsib3cdaia',
    storageBucket: 'epsib3cdaia.appspot.com',
    iosClientId: '626775340202-net3702f0i7gubo0n9qh48mqv6atrsd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectepsi',
  );
}
